debian/rules: remove no longer needed LDFLAGS
Itanium64 isn't a alive any longer as a Debian supported platform, Alpha
is broken on the buildds for a longer time with some libc6 error while
running override_dh_auto_configure since 38.0~b2-1:

cd /«PKGBUILDDIR»/obj-icedove
/«PKGBUILDDIR»/configure
creating cache ./config.cache
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/mozilla/./mach", line 148, in <module>
    main(sys.argv[1:])
  File "/«PKGBUILDDIR»/mozilla/./mach", line 76, in main
    mach = get_mach()
  File "/«PKGBUILDDIR»/mozilla/./mach", line 67, in get_mach
    mach = check_and_get_mach(dir_path)
  File "/«PKGBUILDDIR»/mozilla/./mach", line 42, in check_and_get_mach
    return load_mach(dir_path, mach_path)
  File "/«PKGBUILDDIR»/mozilla/./mach", line 30, in load_mach
    return mach_bootstrap.bootstrap(dir_path)
  File "/«PKGBUILDDIR»/build/mach_bootstrap.py", line 14, in bootstrap
    return build.mach_bootstrap.bootstrap(topsrcdir, mozilla_dir)
  File "/«PKGBUILDDIR»/mozilla/build/mach_bootstrap.py", line 217, in bootstrap
    mach.load_commands_from_file(os.path.join(mozilla_dir, path))
  File "/«PKGBUILDDIR»/mozilla/python/mach/mach/main.py", line 266, in load_commands_from_file
    imp.load_source(module_name, path)
  File "/«PKGBUILDDIR»/mozilla/testing/web-platform/mach_commands.py", line 24, in <module>
    from update import updatecommandline
  File "/«PKGBUILDDIR»/mozilla/testing/web-platform/update/__init__.py", line 17, in <module>
    from wptrunner.update import setup_logging, WPTUpdate
  File "/«PKGBUILDDIR»/mozilla/testing/web-platform/harness/wptrunner/update/__init__.py", line 12, in <module>
    from update import WPTUpdate
  File "/«PKGBUILDDIR»/mozilla/testing/web-platform/harness/wptrunner/update/update.py", line 8, in <module>
    from metadata import MetadataUpdateRunner
  File "/«PKGBUILDDIR»/mozilla/testing/web-platform/harness/wptrunner/update/metadata.py", line 7, in <module>
    from .. import metadata
  File "/«PKGBUILDDIR»/mozilla/testing/web-platform/harness/wptrunner/metadata.py", line 18, in <module>
    import testloader
  File "/«PKGBUILDDIR»/mozilla/testing/web-platform/harness/wptrunner/testloader.py", line 11, in <module>
    import wpttest
  File "/«PKGBUILDDIR»/mozilla/testing/web-platform/harness/wptrunner/wpttest.py", line 10, in <module>
    import mozinfo
  File "/«PKGBUILDDIR»/mozilla/testing/mozbase/mozinfo/mozinfo/__init__.py", line 54, in <module>
    import mozinfo
  File "/«PKGBUILDDIR»/mozilla/testing/mozbase/mozinfo/mozinfo/mozinfo.py", line 99, in <module>
    ctypes.CDLL("libc.so.6", use_errno=True).prctl(PR_SET_SECCOMP, SECCOMP_MODE_FILTER, 0)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libc.so.6: cannot open shared object file: No such file or directory

Removing the LDFLAGS definition for ia64 and alpha as those platforms are not
buildable for long time, this keeps the rules file better readable.